// Code generated by mockery v2.13.0-beta.1. DO NOT EDIT.

package mocks

import (
	models "fizz-buzz-api/models"

	mock "github.com/stretchr/testify/mock"
)

// FizzBuzzService is an autogenerated mock type for the FizzBuzzService type
type FizzBuzzService struct {
	mock.Mock
}

// ComputeFizzBuzz provides a mock function with given fields: request
func (_m *FizzBuzzService) ComputeFizzBuzz(request *models.FizzBuzzRequest) ([]string, error) {
	ret := _m.Called(request)

	var r0 []string
	if rf, ok := ret.Get(0).(func(*models.FizzBuzzRequest) []string); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.FizzBuzzRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type NewFizzBuzzServiceT interface {
	mock.TestingT
	Cleanup(func())
}

// NewFizzBuzzService creates a new instance of FizzBuzzService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFizzBuzzService(t NewFizzBuzzServiceT) *FizzBuzzService {
	mock := &FizzBuzzService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
