// Code generated by mockery v2.13.0-beta.1. DO NOT EDIT.

package mocks

import (
	models "fizz-buzz-api/models"

	mock "github.com/stretchr/testify/mock"
)

// StatisticsService is an autogenerated mock type for the StatisticsService type
type StatisticsService struct {
	mock.Mock
}

// CountRequest provides a mock function with given fields: request
func (_m *StatisticsService) CountRequest(request *models.FizzBuzzRequest) error {
	ret := _m.Called(request)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.FizzBuzzRequest) error); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetStatistics provides a mock function with given fields:
func (_m *StatisticsService) GetStatistics() (*models.StatisticsResponse, error) {
	ret := _m.Called()

	var r0 *models.StatisticsResponse
	if rf, ok := ret.Get(0).(func() *models.StatisticsResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.StatisticsResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type NewStatisticsServiceT interface {
	mock.TestingT
	Cleanup(func())
}

// NewStatisticsService creates a new instance of StatisticsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStatisticsService(t NewStatisticsServiceT) *StatisticsService {
	mock := &StatisticsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
